### PR TITLE
My reservations component

### PR DESCRIPTION
**Pull request by mugberto**
In this branch, I added MyReservation component which lists reservations made by the current user and provides a possibility to cancel a reservation

### CODE REVIEW

**Review by AleksandarIvezic — CHANGES_REQUESTED** [review]
## Hi @mugberto ,

### You did a great job so far, but there are still some things to be improved.

Changes required 🛑 🛑 🛑 

Please make sure that you loaded your data before you start mapping the reservations.

image

In MyReservations you can add something like this 
```
 return (
    <>
      <h2>My Reservations</h2>
      <ul>
        {' '}
        {reservations
        && reservations.map((reservation) => (
          <li key={reservation.id}>
            <span>
...
```

**Review by themonster2015 — CHANGES_REQUESTED** [review]
Hi @mugberto , I think if you make a small change in the code like @ShinobiWarior  suggested, it will work fine with no errors.

` return (
    <>
      <h2>My Reservations</h2>
      <ul>
        {' '}
        {reservations
        && reservations.map((reservation) => (
          <li key={reservation.id}>
            <span>
...
`

**Comment by mugberto** [comment]
Hi @themonster2015, I made the changes and I working fine on my end.

**Review by themonster2015 — APPROVED** [review]
Hi @mugberto I think your code looks fine now 👍

**Pull request closed without merging**
