### PR TITLE
Revert "Style destinations"

### PR DESCRIPTION
**Pull request by danmainah**
Reverts danmainah/vacations-booking-front-end#16

**Closed when solving merge errors**

### CODE REVIEW

**Review by AleksandarIvezic — CHANGES_REQUESTED** [review]
## Hi @danmainah, 
You did a great work here, but I think that this issue is not ready to be closed yet.

Your layout looks like that 
image

and our targeted design is 
image

Can you please make sure that the layout is close as much as possible to the required one, and that it is responsive in different views?

Also please try to use data from our back-end side of the project.

If you have any questions or you want to discuss the changes, please write below in the comments, or reach me on the slack.

Cheers!!! 🥂

**Comment by danmainah** [comment]
What let me check on it ,because on my end is so different

**Review by themonster2015 — COMMENTED** [review]
Hi @danmainah I think after pulling the latest changes you made, the page looks nice.

**Review by AleksandarIvezic — APPROVED** [review]
## Hi @danmainah ,

### Great job. It looks nice now. You can merge it. ✔️ ✔️ ✔️ 

Cheers!!! 🥂

**Pull request merged**
