### PR TITLE
Add message display in add destinations form

### PR DESCRIPTION
**Pull request by igorkol91**
Added new post action in reducers that would add the possibility the server message to be displayed on the front end. The message is in post form component and still in console.log so needs to be finished.

### CODE REVIEW

**Review by danmainah — COMMENTED** [review]
I cant see the console message on my end,would you mind rrechecking it again

**Review by themonster2015 — CHANGES_REQUESTED** [review]
Hi @igorkol91 , I got this error message in the browser when loading the destination form: 
Screen Shot 2021-11-23 at 22 45 10

**Review by danmainah — APPROVED** [review]
Good job @igorkol91

**Review by themonster2015 — APPROVED** [review]
Hi @igorkol91 I checked and it works well now. Good job 👍

**Pull request merged**
