### PR TITLE
Style MyReservations

### PR DESCRIPTION
**Pull request by AleksandarIvezic**
## Changes:
- Refactor MyReservations component
- Update reservation reducers
- Style MyReservations
image
image

### CODE REVIEW

**Review by igorkol91 — CHANGES_REQUESTED** [review]
Hey @ShinobiWarior. It looks good.

The images doesn's seem to be showing.
And i can't see the price or the name
Screenshot at 2021-11-24 08-27-04

**Review by mugberto — APPROVED** [review]
### Approved :+1: 
Hi @ShinobiWarior, Great job on the additional image feature. Make sure the back end provide a response that include the image URL.

**Review by igorkol91 — APPROVED** [review]
It looks awesome now. Great work!

**Review by themonster2015 — APPROVED** [review]
Hi @ShinobiWarior, it looks good on my end as well. Good job 👍

**Pull request merged**
